### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by steefeen** [aws-amplify/amplify-ui-swift-authenticator#51] opened 2024-01-02 17:48 UTC
Hi,

When trying to reset the password the error message "Passwords do not match." is shown, but the passwords do obviously match. (see image) 

Using a version before 1.0.6 I'm able to reset the password.

![IMG_4923](https://github.com/aws-amplify/amplify-ui-swift-authenticator/assets/30449693/6c53f722-31d7-42b6-88a3-32681d79ab49)

**Comment by ruisebas** [comment] 2024-01-03 15:19
Hi @steefeen! Thanks for opening this issue, we'll take a look.

**Comment by ruisebas** [comment] 2024-01-03 17:05
I was unable to reproduce this issue on both the simulator and a physical iPhone, the password is accepted.
![confirmResetPassword](https://github.com/aws-amplify/amplify-ui-swift-authenticator/assets/97059974/6f21d405-3409-4f38-86f0-19546dfcb162)

Are you sure there's no trailing space on either field that's messing up the validation? The validation is performed [here](https://github.com/aws-amplify/amplify-ui-swift-authenticator/blob/main/Sources/Authenticator/Views/ConfirmResetPasswordView.swift#L57-L59), could you set a breakpoint and check what values are set? In that context, `value` is the "Confirm password" field, while `state.newPassword` is the "New password" field.

If the values do differ,  could you please provide some additional details that help us reproduce the situation? Such as:
- Does it happen on a device/simulator only.
- Are there any customizations made to the Authenticator component.
- How is the Authenticator view integrated into your SwiftUI project.

Thanks!

**Comment by steefeen** [comment] 2024-01-03 22:13
After looking into it:
state.newPassword is an empty string
removing the AuthenticatorTheme solves the problem (see #52)

**Comment by ruisebas** [comment] 2024-01-04 15:04
Thanks @steefeen. Closing this in favour of #52 then.

**Closed by ruisebas** 2024-01-04 15:04 UTC
Labels: bug, pending-response
