### ISSUE TITLE
Delivery details destination is nil in custom sign up confirm view

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#62] opened 2024-04-18 07:43 UTC
Background:
- Using Authenticator's state machine with own custom views

Steps to reproduce this issue:
1. Sign up with custom view.  User is redirected to sign up confirmation view -> delivery details destination is available. I can get the destination value and set it in to my text.
2. Kill the app
3. Launch the app again
4. Do the login -> User is redirected in to custom sign up confirmation view

I want to show text like "Activation code is sent to %@" in custom sign up confirmation view but destination is nil.

**Comment by 5d** [comment] 2024-04-18 18:10
Hi @merbula, thank you for bringing this issue to our attention. We will investigate the matter and provide an update once we have gathered more details.

**Comment by ruisebas** [comment] 2024-04-18 20:34
Hi @merbula, the behaviour you described is expected and coming directly from **Amplify Swift**: the delivery details destination is only available during the Sign Up flow, as the code is sent during the flow.

If you attempt to Sign In a non-confirmed user, you'll be instructed to confirm the user but no new code will be sent. Since neither the Authenticator nor Amplify Swift track the state of past authentication flows, there is no details destination information available at that moment.

Having said that, the Authenticator allows you to send a new code by calling `state.sendCode()` in which case a new details destination information becomes available and displayed in the default view. However, it's currently **not** updating the value of `state.deliveryDetails`, which makes it inaccessible for custom views.
This is a bug and I'll work on fixing it.

**Comment by ruisebas** [comment] 2024-04-26 19:39
This has been fixed in [1.1.2](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.1.2), now `deliveryDetails` is populated/updated when a new code is requested.

**Closed by ruisebas** 2024-04-26 19:39 UTC
Labels: bug
