### ISSUE TITLE
Title: Birthdate Attribute Error: String Must Be No Longer Than 10 

### ISSUE THREAD

**Issue by ChrisGSI** [aws-amplify/amplify-ui-swift-authenticator#30] opened 2023-08-16 14:56 UTC
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

iOS

### Which UI component?

Authenticator

### How is your app built?

IOS swift SwiftUI 

### What browsers are you seeing the problem on?

iOS (React Native)

### Which region are you seeing the problem in?

East-1

### Please describe your bug.

When entering a birthdate in the "YYYY-MM-DD" format, an error message is displayed: "Attributes did not conform to the schema: birthdate: String must be no longer than 10 characters." It seems that the birthdate validation expects exactly 10 characters, causing issues with certain date formats.

### What's the expected behaviour?

The expected behavior is for the birthdate in the "YYYY-MM-DD" format to be accepted without errors.

### Help us reproduce the bug!

using the amplify authenticator package with IOS swift swiftui and this error is being thrown when submitting birth date to cognito as an attribute for user creation

### Code Snippet

```typescript
// Put your code below this line.

```

### Console log output

xcode Console log output:
"AuthError: Attributes did not conform to the schema: birthdate: String must be no longer than 10 characters"

**Comment by ChrisGSI** [comment] 2023-08-16 20:59
Thank you

**Comment by ruisebas** [comment] 2023-08-16 22:37
Hi @ChrisGSI , thanks for opening this issue.
I was able to reproduce the issue when the default `.birthDate()` is displayed. It's happening because Swift's `ISO8601DateFormatter` by default includes the time when parsing to a String, but it seems Cognito only wants the date. 
I will work on a fix for this.

However, I'm a bit confused by the description you provided. You said that entering a date with the "YYYY-MM-DD" format is rejected because it exceeds 10 characters. Does this mean you are using a `.custom` SignUpField with `attributeType: .birthDate`, and that typing a date (e.g. "2023-08-16") is rejected, even if it has exactly 10 characters?

**Comment by ruisebas** [comment] 2023-08-18 14:17
[1.0.3](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.0.3) was released fixing the issue with the default `birthDate()` field.

Please let me know if this prevents the error you were getting.

**Comment by ChrisGSI** [comment] 2023-08-22 11:40
Sebastian,
This fixed the issue. Thank you for your support.

Additionally, is there a way to use the amplify authenticator and have the
gender attribute be a picklist field instead of a text field?

**Comment by ruisebas** [comment] 2023-08-22 18:39
Awesome, that's great to hear :) 

Regarding the `.gender()` sign up field, unfortunately the Authenticator only supports rendering it as a TextField out of the box. 

If you wish, you can define your own [`.custom()`](https://github.com/aws-amplify/amplify-ui-swift-authenticator/blob/main/Sources/Authenticator/Models/SignUpField.swift#L482-L491) field that maps to the `.gender` attribute type. Something like this:
```swift
    .custom(
        label: "Gender",
        attributeType: .gender
    ) { binding in
        Picker("Gender", selection: binding) {
            // Your options
        }
    }
```

You can read more about it [here](https://ui.docs.amplify.aws/swift/connected-components/authenticator/customization#field-customization).

Note: There was a bug in which custom fields would not display the label provided, this has been fixed in [`1.0.4`](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.0.4)

**Closed by ruisebas** 2023-08-22 18:39 UTC
Labels: bug, pending-response

**Comment by ChrisGSI** [comment] 2023-08-23 11:22
Thank you for this. To make sure I am clear, I can create a custom field within the amplify authenticator that maps to the standard Cognito attribute for gender? And this custom amplify authenticator field stays a part of the sign in / sign up functionality rendered by the amplify authenticator? 

As opposed to, creating a custom cognito attribute and capturing in that in some later part of the app, after the user has created an account? 

Am I thinking of that correctly?

Thank you again for your help.

**Comment by ruisebas** [comment] 2023-08-25 20:19
> I can create a custom field within the amplify authenticator that maps to the standard Cognito attribute for gender? And this custom amplify authenticator field stays a part of the sign in / sign up functionality rendered by the amplify authenticator?

This only applies to the **Sign Up** view. You can provide the fields by using the `signUpFields(_:)` method. 
For example:
```swift
Authenticator { state in
    // Your signed in content
}
.signUpFields([
    .username(),
    .password(),
    .confirmPassword(),
    .email(),
    .custom(
        label: "Gender",
        attributeType: .gender
    ) { binding in
        Picker("Gender", selection: binding) {
            // Your options. Don't forget to use `.tag(_:)` or have a proper `id` for each
        }
        .onAppear {
            binding.wrappedValue = // your initial value
        }
    }
])
```
